# type: ignore
#
# Auto-generated type stub for __init__.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse SDK 主模块

提供SDK核心功能模块加载和初始化功能

{!--< tips >!--}
1. 使用前请确保已正确安装所有依赖
2. 调用await sdk.init()进行初始化
3. 模块加载采用懒加载机制
{!--< /tips >!--}
"""

import os
import sys
import types
import importlib
import asyncio
import inspect
import importlib.metadata
from typing import Dict, List, Tuple, Type, Any, TYPE_CHECKING
from pathlib import Path
from .Core import Event
from .Core import lifecycle, logger, exceptions
from .Core import storage, env, config
from .Core import adapter, AdapterFather, BaseAdapter, SendDSL
from .Core import module
from .Core import router, adapter_server
from .Core import ux, UXManager

sdk: SDKProtocol

class LazyModule:
    """
    懒加载模块包装器
    
    当模块第一次被访问时才进行实例化
    
    {!--< tips >!--}
    1. 模块的实际实例化会在第一次属性访问时进行
    2. 依赖模块会在被使用时自动初始化
    3. 对于继承自 BaseModule 的模块，会自动调用生命周期方法
    {!--< /tips >!--}
    """
    def __init__(self: None, module_name: str, module_class: Type, sdk_ref: Any, module_info: Dict[(str, Any)]) -> None:
        """
        初始化懒加载包装器
        
        :param module_name: str 模块名称
        :param module_class: Type 模块类
        :param sdk_ref: Any SDK引用
        :param module_info: Dict[str, Any] 模块信息字典
        """
        ...
    async def _initialize(self: object) -> ...:
        """
        实际初始化模块
        
        :raises LazyLoadError: 当模块初始化失败时抛出
        """
        ...
    def _initialize_sync(self: object) -> ...:
        """
        同步初始化模块，用于在异步上下文中进行同步调用
        
        :raises LazyLoadError: 当模块初始化失败时抛出
        """
        ...
    async def _complete_async_init(self: object) -> ...:
        """
        完成异步初始化部分，用于同步初始化后的异步处理
        
        这个方法用于处理 module.load 和事件提交等异步操作
        """
        ...
    def _ensure_initialized(self: object) -> None:
        """
        确保模块已初始化
        
        :raises LazyLoadError: 当模块未初始化时抛出
        """
        ...
    def __getattr__(self: object, name: str) -> Any:
        """
        属性访问时触发初始化
        
        :param name: str 属性名
        :return: Any 属性值
        """
        ...
    def __setattr__(self: object, name: str, value: Any) -> None:
        """
        属性设置
        
        :param name: str 属性名
        :param value: Any 属性值
        """
        ...
    def __delattr__(self: object, name: str) -> None:
        """
        属性删除
        
        :param name: str 属性名
        """
        ...
    def __getattribute__(self: object, name: str) -> Any:
        """
        属性访问，初始化后直接委托给实际实例
        
        :param name: str 属性名
        :return: Any 属性值
        """
        ...
    def __dir__(self: object) -> List[str]:
        """
        返回模块属性列表
        
        :return: List[str] 属性列表
        """
        ...
    def __repr__(self: object) -> str:
        """
        返回模块表示字符串
        
        :return: str 表示字符串
        """
        ...
    def __call__(self: object, *args: ..., **kwargs: ...) -> ...:
        """
        代理函数调用
        """
        ...

class AdapterLoader:
    """
    适配器加载器
    
    专门用于从PyPI包加载和初始化适配器
    
    {!--< tips >!--}
    1. 适配器必须通过entry-points机制注册到erispulse.adapter组
    2. 适配器类必须继承BaseAdapter
    3. 适配器不适用懒加载
    {!--< /tips >!--}
    """
    async def load() -> Tuple[(Dict[(str, object)], List[str], List[str])]:
        """
        从PyPI包entry-points加载适配器
        
        :return: 
            Dict[str, object]: 适配器对象字典 {适配器名: 模块对象}
            List[str]: 启用的适配器名称列表
            List[str]: 停用的适配器名称列表
            
        :raises ImportError: 当无法加载适配器时抛出
        """
        ...

class ModuleLoader:
    """
    模块加载器
    
    专门用于从PyPI包加载和初始化普通模块
    
    {!--< tips >!--}
    1. 模块必须通过entry-points机制注册到erispulse.module组
    2. 模块类名应与entry-point名称一致
    {!--< /tips >!--}
    """
    async def load() -> Tuple[(Dict[(str, object)], List[str], List[str])]:
        """
        从PyPI包entry-points加载模块
        
        :return: 
            Dict[str, object]: 模块对象字典 {模块名: 模块对象}
            List[str]: 启用的模块名称列表
            List[str]: 停用的模块名称列表
            
        :raises ImportError: 当无法加载模块时抛出
        """
        ...
    def _should_lazy_load(module_class: Type) -> bool:
        """
        检查模块是否应该懒加载
        
        :param module_class: Type 模块类
        :return: bool 如果返回 False，则立即加载；否则懒加载
        """
        ...

class ModuleInitializer:
    """
    模块初始化器（注意：适配器是一个特殊的模块）
    
    负责协调适配器和模块的初始化流程
    
    {!--< tips >!--}
    1. 初始化顺序：适配器 → 模块
    2. 模块初始化采用懒加载机制
    {!--< /tips >!--}
    """
    async def init() -> bool:
        """
        初始化所有模块和适配器
        
        执行步骤:
        1. 从PyPI包加载适配器
        2. 从PyPI包加载模块
        3. 预记录所有模块信息
        4. 注册适配器
        5. 初始化各模块
        
        :return: bool 初始化是否成功
        :raises InitError: 当初始化失败时抛出
        """
        ...

async def init_progress() -> bool:
    """
    初始化项目环境文件
    
    1. 检查并创建main.py入口文件
    2. 确保基础目录结构存在
    
    :return: bool 是否创建了新的main.py文件
    
    {!--< tips >!--}
    1. 如果main.py已存在则不会覆盖
    2. 此方法通常由SDK内部调用
    {!--< /tips >!--}
    """
    ...

async def init() -> bool:
    """
    SDK初始化入口
    
    :return: bool SDK初始化是否成功
    """
    ...

def init_sync() -> bool:
    """
    SDK初始化入口（同步版本）
    
    用于命令行直接调用，自动在事件循环中运行异步初始化
    
    :return: bool SDK初始化是否成功
    """
    ...

def init_task() -> asyncio.Task:
    """
    SDK初始化入口，返回Task对象
    
    :return: asyncio.Task 初始化任务
    """
    ...

async def uninit() -> bool:
    """
    SDK反初始化
    
    执行以下操作：
    1. 关闭所有适配器
    2. 卸载所有模块
    3. 清理所有事件处理器
    4. 清理僵尸线程
    
    :return: bool 反初始化是否成功
    """
    ...

async def restart() -> bool:
    """
    SDK重新启动
    
    执行完整的反初始化后再初始化过程
    
    :return: bool 重新加载是否成功
    """
    ...

async def run(keep_running: bool = ...) -> None:
    """
    无头模式运行ErisPulse
    
    此方法提供了一种无需入口启动的方式，适用于与其它框架集成的场景
    """
    ...

async def load_module(module_name: str) -> bool:
    """
    手动加载指定模块
    
    :param module_name: str 要加载的模块名称
    :return: bool 加载是否成功
    
    {!--< tips >!--}
    1. 可用于手动触发懒加载模块的初始化
    2. 如果模块不存在或已加载会返回False
    3. 对于需要异步初始化的模块，这是唯一的加载方式
    {!--< /tips >!--}
    """
    ...
