# type: ignore
#
# Auto-generated type stub for sdk_protocol.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse SDK Protocol 定义

提供 SDK 的类型接口定义，用于 IDE 类型提示和静态类型检查
"""

from typing import Protocol, runtime_checkable, Any, TypeVar
from typing_extensions import ParamSpec
import asyncio
from .Core.Event import Event as EventType
from .Core.lifecycle import LifecycleManager
from .Core.logger import Logger
from .Core.storage import StorageManager
from .Core.config import ConfigManager
from .Core.adapter import AdapterManager
from .Core.module import ModuleManager
from .Core.router import RouterManager
from .Core.Bases.adapter import BaseAdapter, SendDSL

class SDKProtocol(Protocol):
    """
    SDK 对象的 Protocol 接口定义
    
    定义了 SDK 对象应该具有的所有属性和方法，用于类型检查
    """
    Event: type[EventType]
    lifecycle: LifecycleManager
    logger: Logger
    exceptions: Any
    storage: StorageManager
    env: StorageManager
    config: ConfigManager
    adapter: AdapterManager
    AdapterFather: type[BaseAdapter]
    BaseAdapter: type[BaseAdapter]
    SendDSL: type[SendDSL]
    module: ModuleManager
    router: RouterManager
    adapter_server: RouterManager
    async def init(self: object) -> bool:
        """
        SDK初始化入口
        
        :return: bool SDK初始化是否成功
        """
        ...
    def init_task(self: object) -> asyncio.Task:
        """
        SDK初始化入口，返回Task对象
        
        :return: asyncio.Task 初始化任务
        """
        ...
    async def load_module(self: object, module_name: str) -> bool:
        """
        手动加载指定模块
        
        :param module_name: str 要加载的模块名称
        :return: bool 加载是否成功
        """
        ...
    async def run(self: object, keep_running: bool = ...) -> None:
        """
        无头模式运行ErisPulse
        
        :param keep_running: bool 是否保持运行
        """
        ...
    async def restart(self: object) -> bool:
        """
        SDK重新启动
        
        :return: bool 重新加载是否成功
        """
        ...
    async def uninit(self: object) -> bool:
        """
        SDK反初始化
        
        :return: bool 反初始化是否成功
        """
        ...

def check_sdk_compatible(obj: Any) -> bool:
    """
    检查对象是否符合 SDK Protocol
    
    :param obj: 要检查的对象
    :return: bool 是否符合协议
    """
    ...
