# type: ignore
#
# Auto-generated type stub for console.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

import sys
from rich.console import Console
from rich.theme import Theme
from rich.highlighter import RegexHighlighter

class CommandHighlighter(RegexHighlighter):
    """
    高亮CLI命令和参数
    
    {!--< tips >!--}
    使用正则表达式匹配命令行参数和选项
    {!--< /tips >!--}
    """
    ...
