# type: ignore
#
# Auto-generated type stub for reload_handler.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse SDK 热重载处理器

实现热重载功能，监控文件变化并重启进程
"""

import os
import subprocess
import sys
import time
from watchdog.events import FileSystemEventHandler
from .console import console

class ReloadHandler(FileSystemEventHandler):
    """
    文件系统事件处理器
    
    实现热重载功能，监控文件变化并重启进程
    
    {!--< tips >!--}
    1. 支持.py文件修改重载
    2. 支持配置文件修改重载
    {!--< /tips >!--}
    """
    def __init__(self: None, script_path: str, reload_mode: bool = ...) -> ...:
        """
        初始化处理器
        
        :param script_path: 要监控的脚本路径
        :param reload_mode: 是否启用重载模式
        """
        ...
    def start_process(self: object) -> ...:
        """
        启动监控进程
        """
        ...
    def _terminate_process(self: object) -> ...:
        """
        终止当前进程
        
        :raises subprocess.TimeoutExpired: 进程终止超时时抛出
        """
        ...
    def on_modified(self: object, event: ...) -> ...:
        """
        文件修改事件处理
        
        :param event: 文件系统事件
        """
        ...
    def _handle_reload(self: object, event: ..., reason: str) -> ...:
        """
        处理热重载逻辑
        :param event: 文件系统事件
        :param reason: 重载原因
        """
        ...
