# type: ignore
#
# Auto-generated type stub for command.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 命令处理模块

提供基于装饰器的命令注册和处理功能

{!--< tips >!--}
1. 支持命令别名和命令组
2. 支持命令权限控制
3. 支持命令帮助系统
4. 支持等待用户回复交互
{!--< /tips >!--}
"""

from .base import BaseEventHandler
from .. import adapter, config, logger
from typing import Callable, Union, List, Dict, Any, Optional, Awaitable
import asyncio

class CommandHandler:
    """
    命令处理器
    
    提供命令注册、处理和管理功能
    """
    def __init__(self: None) -> ...:
        ...
    def __call__(self: object, name: Union[(str, List[str])] = ..., aliases: List[str] = ..., group: str = ..., priority: int = ..., permission: Callable = ..., help: str = ..., usage: str = ..., hidden: bool = ...) -> ...:
        """
        命令装饰器
        
        :param name: 命令名称，可以是字符串或字符串列表
        :param aliases: 命令别名列表
        :param group: 命令组名称
        :param priority: 处理器优先级
        :param permission: 权限检查函数，返回True时允许执行命令
        :param help: 命令帮助信息
        :param usage: 命令使用方法
        :param hidden: 是否在帮助中隐藏命令
        :return: 装饰器函数
        """
        ...
    def unregister(self: object, handler: Callable) -> bool:
        """
        注销命令处理器
        
        :param handler: 要注销的命令处理器
        :return: 是否成功注销
        """
        ...
    async def wait_reply(self: object, event: Dict[(str, Any)], prompt: str = ..., timeout: float = ..., callback: Callable[([Dict[(str, Any)]], Awaitable[Any])] = ..., validator: Callable[([Dict[(str, Any)]], bool)] = ...) -> Optional[Dict[(str, Any)]]:
        """
        等待用户回复
        
        :param event: 原始事件数据
        :param prompt: 提示消息，如果提供会发送给用户
        :param timeout: 等待超时时间(秒)
        :param callback: 回调函数，当收到回复时执行
        :param validator: 验证函数，用于验证回复是否有效
        :return: 用户回复的事件数据，如果超时则返回None
        """
        ...
    async def _check_pending_reply(self: object, event: Dict[(str, Any)]) -> ...:
        """
        检查是否是等待回复的消息
        
        :param event: 消息事件数据
        """
        ...
    def get_command(self: object, name: str) -> Optional[Dict]:
        """
        获取命令信息
        
        :param name: 命令名称
        :return: 命令信息字典，如果不存在则返回None
        """
        ...
    def get_commands(self: object) -> Dict[(str, Dict)]:
        """
        获取所有命令
        
        :return: 命令信息字典
        """
        ...
    def get_group_commands(self: object, group: str) -> List[str]:
        """
        获取命令组中的命令
        
        :param group: 命令组名称
        :return: 命令名称列表
        """
        ...
    def get_visible_commands(self: object) -> Dict[(str, Dict)]:
        """
        获取所有可见命令（非隐藏命令）
        
        :return: 可见命令信息字典
        """
        ...
    def help(self: object, command_name: str = ..., show_hidden: bool = ...) -> str:
        """
        生成帮助信息
        
        :param command_name: 命令名称，如果为None则生成所有命令的帮助
        :param show_hidden: 是否显示隐藏命令
        :return: 帮助信息字符串
        """
        ...
