# type: ignore
#
# Auto-generated type stub for message.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 消息处理模块

提供基于装饰器的消息事件处理功能

{!--< tips >!--}
1. 支持私聊、群聊消息分类处理
2. 支持@消息特殊处理
3. 支持自定义条件过滤
{!--< /tips >!--}
"""

from .base import BaseEventHandler
from typing import Callable, Dict, Any

class MessageHandler:
    """
    消息事件处理器
    
    提供不同类型消息事件的处理功能
    """
    def __init__(self: None) -> ...:
        ...
    def on_message(self: object, priority: int = ...) -> ...:
        """
        消息事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_message_handler(self: object, handler: Callable) -> bool:
        """
        取消注册消息事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_private_message(self: object, priority: int = ...) -> ...:
        """
        私聊消息事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_private_message_handler(self: object, handler: Callable) -> bool:
        """
        取消注册私聊消息事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_group_message(self: object, priority: int = ...) -> ...:
        """
        群聊消息事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_group_message_handler(self: object, handler: Callable) -> bool:
        """
        取消注册群聊消息事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_at_message(self: object, priority: int = ...) -> ...:
        """
        @消息事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_at_message_handler(self: object, handler: Callable) -> bool:
        """
        取消注册@消息事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
