# type: ignore
#
# Auto-generated type stub for notice.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 通知处理模块

提供基于装饰器的通知事件处理功能

{!--< tips >!--}
1. 支持好友、群组等不同类型通知
2. 支持成员变动等细粒度事件
{!--< /tips >!--}
"""

from .base import BaseEventHandler
from typing import Callable, Dict, Any

class NoticeHandler:
    """
    通知事件处理器
    
    提供通知事件处理功能
    """
    def __init__(self: None) -> ...:
        ...
    def on_notice(self: object, priority: int = ...) -> ...:
        """
        通用通知事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_notice_handler(self: object, handler: Callable) -> bool:
        """
        取消注册通用通知事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_friend_add(self: object, priority: int = ...) -> ...:
        """
        好友添加通知事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_friend_add_handler(self: object, handler: Callable) -> bool:
        """
        取消注册好友添加通知事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_friend_remove(self: object, priority: int = ...) -> ...:
        """
        好友删除通知事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_friend_remove_handler(self: object, handler: Callable) -> bool:
        """
        取消注册好友删除通知事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_group_increase(self: object, priority: int = ...) -> ...:
        """
        群成员增加通知事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_group_increase_handler(self: object, handler: Callable) -> bool:
        """
        取消注册群成员增加通知事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_group_decrease(self: object, priority: int = ...) -> ...:
        """
        群成员减少通知事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_group_decrease_handler(self: object, handler: Callable) -> bool:
        """
        取消注册群成员减少通知事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
