# type: ignore
#
# Auto-generated type stub for adapter.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 适配器系统

提供平台适配器管理功能。支持多平台消息处理、事件驱动和生命周期管理。
"""

import functools
import asyncio
from typing import Callable, Any, Dict, List, Type, Optional, Set
from collections import defaultdict
from .logger import logger
from .Bases.adapter import BaseAdapter
from .config import config
from .lifecycle import lifecycle

class AdapterManager:
    """
    适配器管理器
    
    管理多个平台适配器的注册、启动和关闭，提供与模块管理器一致的接口
    
    {!--< tips >!--}
    1. 通过register方法注册适配器
    2. 通过startup方法启动适配器
    3. 通过shutdown方法关闭所有适配器
    4. 通过on装饰器注册OneBot12协议事件处理器
    {!--< /tips >!--}
    """
    def __init__(self: None) -> ...:
        ...
    def register(self: object, platform: str, adapter_class: Type[BaseAdapter], adapter_info: Optional[Dict] = ...) -> bool:
        """
        注册新的适配器类（标准化注册方法）
        
        :param platform: 平台名称
        :param adapter_class: 适配器类
        :param adapter_info: 适配器信息
        :return: 注册是否成功
        
        :raises TypeError: 当适配器类无效时抛出
        
        :example:
        >>> adapter.register("MyPlatform", MyPlatformAdapter)
        """
        ...
    def _register_platform_attributes(self: object, platform: str, instance: BaseAdapter) -> None:
        """
        注册平台名称的多种大小写形式作为属性
        
        :param platform: 平台名称
        :param instance: 适配器实例
        """
        ...
    async def startup(self: object, platforms: ... = ...) -> None:
        """
        启动指定的适配器
        
        :param platforms: 要启动的平台列表，None表示所有平台
        
        :raises ValueError: 当平台未注册时抛出
        
        :example:
        >>> # 启动所有适配器
        >>> await adapter.startup()
        >>> # 启动指定适配器
        >>> await adapter.startup(["Platform1", "Platform2"])
        """
        ...
    async def shutdown(self: object) -> None:
        """
        关闭所有适配器
        """
        ...
    def _config_register(self: object, platform: str, enabled: bool = ...) -> bool:
        """
        注册新平台适配器（仅当平台不存在时注册）
        
        :param platform: 平台名称
        :param enabled: [bool] 是否启用适配器
        :return: [bool] 操作是否成功
        """
        ...
    def exists(self: object, platform: str) -> bool:
        """
        检查平台是否存在
        
        :param platform: 平台名称
        :return: [bool] 平台是否存在
        """
        ...
    def is_enabled(self: object, platform: str) -> bool:
        """
        检查平台适配器是否启用
        
        :param platform: 平台名称
        :return: [bool] 平台适配器是否启用
        """
        ...
    def enable(self: object, platform: str) -> bool:
        """
        启用平台适配器
        
        :param platform: 平台名称
        :return: [bool] 操作是否成功
        """
        ...
    def disable(self: object, platform: str) -> bool:
        """
        禁用平台适配器
        
        :param platform: 平台名称
        :return: [bool] 操作是否成功
        """
        ...
    def list_adapters(self: object) -> Dict[(str, bool)]:
        """
        列出所有平台适配器状态
        
        :return: [Dict[str, bool]] 平台适配器状态字典
        """
        ...
    def on(self: object, event_type: str = ...) -> Callable[([Callable], Callable)]:
        """
        OneBot12协议事件监听装饰器
        
        :param event_type: OneBot12事件类型
        :param raw: 是否监听原生事件
        :param platform: 指定平台，None表示监听所有平台
        :return: 装饰器函数
        
        :example:
        >>> # 监听OneBot12标准事件（所有平台）
        >>> @sdk.adapter.on("message")
        >>> async def handle_message(data):
        >>>     print(f"收到OneBot12消息: {data}")
        >>>
        >>> # 监听特定平台的OneBot12标准事件
        >>> @sdk.adapter.on("message", platform="onebot11")
        >>> async def handle_onebot11_message(data):
        >>>     print(f"收到OneBot11标准消息: {data}")
        >>>
        >>> # 监听平台原生事件
        >>> @sdk.adapter.on("message", raw=True, platform="onebot11")
        >>> async def handle_raw_message(data):
        >>>     print(f"收到OneBot11原生事件: {data}")
        >>>
        >>> # 监听所有平台的原生事件
        >>> @sdk.adapter.on("message", raw=True)
        >>> async def handle_all_raw_message(data):
        >>>     print(f"收到原生事件: {data}")
        """
        ...
    def middleware(self: object, func: Callable) -> Callable:
        """
        添加OneBot12中间件处理器
        
        :param func: 中间件函数
        :return: 中间件函数
        
        :example:
        >>> @sdk.adapter.middleware
        >>> async def onebot_middleware(data):
        >>>     print("处理OneBot12数据:", data)
        >>>     return data
        """
        ...
    async def emit(self: object, data: Any) -> None:
        """
        提交OneBot12协议事件到指定平台
        
        :param data: 符合OneBot12标准的事件数据
        
        :example:
        >>> await sdk.adapter.emit({
        >>>     "id": "123",
        >>>     "time": 1620000000,
        >>>     "type": "message",
        >>>     "detail_type": "private",
        >>>     "message": [{"type": "text", "data": {"text": "Hello"}}],
        >>>     "platform": "myplatform",
        >>>     "myplatform_raw": {...平台原生事件数据...},
        >>>     "myplatform_raw_type": "text_message"
        >>> })
        """
        ...
    def get(self: object, platform: str) -> Optional[BaseAdapter]:
        """
        获取指定平台的适配器实例
        
        :param platform: 平台名称
        :return: 适配器实例或None
        
        :example:
        >>> adapter = adapter.get("MyPlatform")
        """
        ...
    def platforms(self: object) -> List[str]:
        """
        获取所有已注册的平台列表
        
        :return: 平台名称列表
        
        :example:
        >>> print("已注册平台:", adapter.platforms)
        """
        ...
    def __getattr__(self: object, platform: str) -> BaseAdapter:
        """
        通过属性访问获取适配器实例
        
        :param platform: 平台名称
        :return: 适配器实例
        :raises AttributeError: 当平台不存在或未启用时
        """
        ...
    def __contains__(self: object, platform: str) -> bool:
        """
        检查平台是否存在且处于启用状态
        
        :param platform: 平台名称
        :return: [bool] 平台是否存在且启用
        """
        ...
