# type: ignore
#
# Auto-generated type stub for logger.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 日志系统

提供模块化日志记录功能，支持多级日志、模块过滤和内存存储。

{!--< tips >!--}
1. 支持按模块设置不同日志级别
2. 日志可存储在内存中供后续分析
3. 自动识别调用模块名称
{!--< /tips >!--}
"""

import logging
import inspect
import datetime
from rich.logging import RichHandler
from rich.console import Console

class Logger:
    """
    日志管理器
    
    提供模块化日志记录和存储功能
    
    {!--< tips >!--}
    1. 使用set_module_level设置模块日志级别
    2. 使用get_logs获取历史日志
    3. 支持标准日志级别(DEBUG, INFO等)
    {!--< /tips >!--}
    """
    def __init__(self: None) -> ...:
        ...
    def set_memory_limit(self: object, limit: int) -> bool:
        """
        设置日志内存存储上限
        
        :param limit: 日志存储上限
        :return: bool 设置是否成功
        """
        ...
    def set_level(self: object, level: str) -> bool:
        """
        设置全局日志级别
        
        :param level: 日志级别(DEBUG/INFO/WARNING/ERROR/CRITICAL)
        :return: bool 设置是否成功
        """
        ...
    def set_module_level(self: object, module_name: str, level: str) -> bool:
        """
        设置指定模块日志级别
        
        :param module_name: 模块名称
        :param level: 日志级别(DEBUG/INFO/WARNING/ERROR/CRITICAL)
        :return: bool 设置是否成功
        """
        ...
    def set_output_file(self: object, path: ...) -> bool:
        """
        设置日志输出
        
        :param path: 日志文件路径 Str/List
        :return: bool 设置是否成功
        """
        ...
    def save_logs(self: object, path: ...) -> bool:
        """
        保存所有在内存中记录的日志
        
        :param path: 日志文件路径 Str/List
        :return: bool 设置是否成功
        """
        ...
    def get_logs(self: object, module_name: str = ...) -> dict:
        """
        获取日志内容
        
        :param module_name (可选): 模块名称
        :return: dict 日志内容
        """
        ...
    def _save_in_memory(self: object, ModuleName: ..., msg: ...) -> ...:
        ...
    def _setup_config(self: object) -> ...:
        ...
    def _get_effective_level(self: object, module_name: ...) -> ...:
        ...
    def _get_caller(self: object) -> ...:
        ...
    def get_child(self: object, child_name: str = ...) -> ...:
        """
        获取子日志记录器
        
        :param child_name: 子模块名称(可选)
        :return: LoggerChild 子日志记录器实例
        """
        ...
    def debug(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def info(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def warning(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def error(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def critical(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        """
        记录 CRITICAL 级别日志
        这是最高级别的日志，表示严重的系统错误
        注意：此方法不会触发程序崩溃，仅记录日志
        
        {!--< tips >!--}
        1. 这是最高级别的日志，表示严重系统错误
        2. 不会触发程序崩溃，如需终止程序请显式调用 sys.exit()
        3. 会在日志文件中添加 CRITICAL 标记便于后续分析
        {!--< /tips >!--}
        """
        ...

class LoggerChild:
    """
    子日志记录器
    
    用于创建具有特定名称的子日志记录器，仅改变模块名称，其他功能全部委托给父日志记录器
    """
    def __init__(self: None, parent_logger: Logger, name: str) -> ...:
        """
        初始化子日志记录器
        
        :param parent_logger: 父日志记录器实例
        :param name: 子日志记录器名称
        """
        ...
    def debug(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def info(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def warning(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def error(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        ...
    def critical(self: object, msg: ..., *args: ..., **kwargs: ...) -> ...:
        """
        记录 CRITICAL 级别日志
        这是最高级别的日志，表示严重的系统错误
        注意：此方法不会触发程序崩溃，仅记录日志
        
        {!--< tips >!--}
        1. 这是最高级别的日志，表示严重系统错误
        2. 不会触发程序崩溃，如需终止程序请显式调用 sys.exit()
        3. 会在日志文件中添加 CRITICAL 标记便于后续分析
        {!--< /tips >!--}
        """
        ...
    def get_child(self: object, child_name: str) -> ...:
        """
        获取子日志记录器的子记录器
        
        :param child_name: 子模块名称
        :return: LoggerChild 子日志记录器实例
        """
        ...
