# type: ignore
#
# Auto-generated type stub for module.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 模块系统

提供标准化的模块注册、加载和管理功能，与适配器系统保持一致的设计模式
"""

import asyncio
from typing import Any, Dict, List, Type, Optional
from .logger import logger
from .config import config
from .Bases import BaseModule
from .lifecycle import lifecycle

class ModuleManager:
    """
    模块管理器
    
    提供标准化的模块注册、加载和管理功能，模仿适配器管理器的模式
    
    {!--< tips >!--}
    1. 使用register方法注册模块类
    2. 使用load/unload方法加载/卸载模块
    3. 通过get方法获取模块实例
    {!--< /tips >!--}
    """
    def __init__(self: None) -> ...:
        ...
    def register(self: object, module_name: str, module_class: Type, module_info: Optional[Dict] = ...) -> bool:
        """
        注册模块类
        
        :param module_name: 模块名称
        :param module_class: 模块类
        :param module_info: 模块信息
        :return: 是否注册成功
        
        :raises TypeError: 当模块类无效时抛出
            
        :example:
        >>> module.register("MyModule", MyModuleClass)
        """
        ...
    async def load(self: object, module_name: str) -> bool:
        """
        加载指定模块（标准化加载逻辑）
        
        :param module_name: 模块名称
        :return: 是否加载成功
            
        :example:
        >>> await module.load("MyModule")
        """
        ...
    async def unload(self: object, module_name: str = ...) -> bool:
        """
        卸载指定模块或所有模块
        
        :param module_name: 模块名称，如果为None则卸载所有模块
        :return: 是否卸载成功
            
        :example:
        >>> await module.unload("MyModule")
        >>> await module.unload()  # 卸载所有模块
        """
        ...
    def get(self: object, module_name: str) -> Any:
        """
        获取模块实例
        
        :param module_name: 模块名称
        :return: 模块实例或None
            
        :example:
        >>> my_module = module.get("MyModule")
        """
        ...
    def exists(self: object, module_name: str) -> bool:
        """
        检查模块是否存在（在配置中注册）
        
        :param module_name: [str] 模块名称
        :return: [bool] 模块是否存在
        """
        ...
    def is_loaded(self: object, module_name: str) -> bool:
        """
        检查模块是否已加载
        
        :param module_name: 模块名称
        :return: 模块是否已加载
            
        :example:
        >>> if module.is_loaded("MyModule"): ...
        """
        ...
    def list_registered(self: object) -> List[str]:
        """
        列出所有已注册的模块
        
        :return: 模块名称列表
            
        :example:
        >>> registered = module.list_registered()
        """
        ...
    def list_loaded(self: object) -> List[str]:
        """
        列出所有已加载的模块
        
        :return: 模块名称列表
            
        :example:
        >>> loaded = module.list_loaded()
        """
        ...
    def _config_register(self: object, module_name: str, enabled: bool = ...) -> bool:
        """
        注册新模块信息
        
        :param module_name: [str] 模块名称
        :param enabled: [bool] 是否启用模块
        :return: [bool] 操作是否成功
        """
        ...
    def is_enabled(self: object, module_name: str) -> bool:
        """
        检查模块是否启用
        
        :param module_name: [str] 模块名称
        :return: [bool] 模块是否启用
        """
        ...
    def enable(self: object, module_name: str) -> bool:
        """
        启用模块
        
        :param module_name: [str] 模块名称
        :return: [bool] 操作是否成功
        """
        ...
    def disable(self: object, module_name: str) -> bool:
        """
        禁用模块
        
        :param module_name: [str] 模块名称
        :return: [bool] 操作是否成功
        """
        ...
    def list_modules(self: object) -> Dict[(str, bool)]:
        """
        列出所有模块状态
        
        :return: [Dict[str, bool]] 模块状态字典
        """
        ...
    def __getattr__(self: object, module_name: str) -> Any:
        """
        通过属性访问获取模块实例
        
        :param module_name: [str] 模块名称
        :return: [Any] 模块实例
        :raises AttributeError: 当模块不存在或未启用时
        """
        ...
    def __contains__(self: object, module_name: str) -> bool:
        """
        检查模块是否存在且处于启用状态
        
        :param module_name: [str] 模块名称
        :return: [bool] 模块是否存在且启用
        """
        ...
