# type: ignore
#
# Auto-generated type stub for router.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 路由系统

提供统一的HTTP和WebSocket路由管理，支持多适配器路由注册和生命周期管理。

{!--< tips >!--}
1. 适配器只需注册路由，无需自行管理服务器
2. WebSocket支持自定义认证逻辑
{!--< /tips >!--}
"""

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.routing import APIRoute
from typing import Dict, List, Optional, Callable, Any, Awaitable, Tuple
from collections import defaultdict
from .logger import logger
from .lifecycle import lifecycle
import asyncio
from hypercorn.config import Config
from hypercorn.asyncio import serve

class RouterManager:
    """
    路由管理器
    
    {!--< tips >!--}
    核心功能：
    - HTTP/WebSocket路由注册
    - 生命周期管理
    - 统一错误处理
    {!--< /tips >!--}
    """
    def __init__(self: None) -> ...:
        """
        初始化路由管理器
        
        {!--< tips >!--}
        会自动创建FastAPI实例并设置核心路由
        {!--< /tips >!--}
        """
        ...
    def register_http_route(self: object, module_name: str, path: str, handler: Callable, methods: List[str] = ...) -> None:
        """
        注册HTTP路由
        
        :param module_name: str 模块名称
        :param path: str 路由路径
        :param handler: Callable 处理函数
        :param methods: List[str] HTTP方法列表(默认["POST"])
        
        :raises ValueError: 当路径已注册时抛出
        """
        ...
    def register_webhook(self: object, *args: ..., **kwargs: ...) -> None:
        """
        兼容性方法：注册HTTP路由（适配器旧接口）
        """
        ...
    def unregister_http_route(self: object, module_name: str, path: str) -> bool:
        """
        取消注册HTTP路由
        
        :param module_name: 模块名称
        :param path: 路由路径
        
        :return: Bool
        """
        ...
    def register_websocket(self: object, module_name: str, path: str, handler: Callable[([WebSocket], Awaitable[Any])], auth_handler: Optional[Callable[([WebSocket], Awaitable[bool])]] = ...) -> None:
        """
        注册WebSocket路由
        
        :param module_name: str 模块名称
        :param path: str WebSocket路径
        :param handler: Callable[[WebSocket], Awaitable[Any]] 主处理函数
        :param auth_handler: Optional[Callable[[WebSocket], Awaitable[bool]]] 认证函数
        
        :raises ValueError: 当路径已注册时抛出
        """
        ...
    def unregister_websocket(self: object, module_name: str, path: str) -> bool:
        ...
    def get_app(self: object) -> FastAPI:
        """
        获取FastAPI应用实例
        
        :return: FastAPI应用实例
        """
        ...
    async def start(self: object, host: str = ..., port: int = ..., ssl_certfile: Optional[str] = ..., ssl_keyfile: Optional[str] = ...) -> None:
        """
        启动路由服务器
        
        :param host: str 监听地址(默认"0.0.0.0")
        :param port: int 监听端口(默认8000)
        :param ssl_certfile: Optional[str] SSL证书路径
        :param ssl_keyfile: Optional[str] SSL密钥路径
        
        :raises RuntimeError: 当服务器已在运行时抛出
        """
        ...
    async def stop(self: object) -> None:
        """
        停止服务器
        """
        ...
    def _format_display_url(self: object, url: str) -> str:
        """
        格式化URL显示，将回环地址转换为更友好的格式
        
        :param url: 原始URL
        :return: 格式化后的URL
        """
        ...
