# type: ignore
#
# Auto-generated type stub for ux.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse UX优化模块

提供更友好的初始化和API接口，简化常用操作
"""

import json
import asyncio
from typing import List, Dict
from pathlib import Path
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.prompt import Confirm

class UXManager:
    """
    UX优化管理器
    
    提供用户友好的界面和简化操作
    """
    def __init__(self: None) -> ...:
        ...
    async def _fetch_available_adapters(self: object) -> Dict[(str, str)]:
        """
        从云端获取可用适配器列表
        
        :return: 适配器名称到描述的映射
        """
        ...
    def welcome(self: object, version: str = ...) -> None:
        """
        显示欢迎信息
        
        :param version: 框架版本号
        """
        ...
    def show_status(self: object) -> None:
        """
        显示系统状态概览
        """
        ...
    def list_modules(self: object, detailed: bool = ...) -> None:
        """
        列出所有模块状态
        
        :param detailed: 是否显示详细信息
        """
        ...
    def list_adapters(self: object, detailed: bool = ...) -> None:
        """
        列出所有适配器状态
        
        :param detailed: 是否显示详细信息
        """
        ...
    def init_project(self: object, project_name: str, adapter_list: List[str] = ...) -> bool:
        """
        初始化新项目
        
        :param project_name: 项目名称
        :param adapter_list: 需要初始化的适配器列表
        :return: 是否初始化成功
        """
        ...
    def interactive_init(self: object, project_name: str = ..., force: bool = ...) -> bool:
        """
        交互式初始化项目，包括项目创建和配置设置
        
        :param project_name: 项目名称，可为None
        :param force: 是否强制覆盖现有配置
        :return: 是否初始化成功
        """
        ...
    def _configure_adapters_interactive_sync(self: object, project_path: str = ...) -> None:
        """
        交互式配置适配器的同步版本，从云端获取适配器列表
        
        :param project_path: 项目路径，用于加载项目特定的配置
        """
        ...
    async def _configure_adapters_interactive(self: object, project_path: str = ...) -> None:
        """
        交互式配置适配器，从云端获取适配器列表
        
        :param project_path: 项目路径，用于加载项目特定的配置
        """
        ...
