# type: ignore
#
# Auto-generated type stub for install.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Install 命令实现

支持交互式和批量安装模块、适配器、CLI 扩展
"""

import sys
import asyncio
from argparse import ArgumentParser
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table
from rich.box import SIMPLE
from ..utils import PackageManager
from ..console import console
from ..base import Command

class InstallCommand(Command):
    def __init__(self: None) -> ...:
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        ...
    def execute(self: object, args: ...) -> ...:
        ...
    def _interactive_install(self: object, upgrade: bool = ..., pre: bool = ...) -> ...:
        """
        交互式安装界面
        
        :param upgrade: 是否升级模式
        :param pre: 是否包含预发布版本
        """
        ...
    def _install_adapters(self: object, remote_packages: dict, upgrade: bool, pre: bool) -> ...:
        """
        安装适配器
        """
        ...
    def _install_modules(self: object, remote_packages: dict, upgrade: bool, pre: bool) -> ...:
        """
        安装模块
        """
        ...
    def _install_cli_extensions(self: object, remote_packages: dict, upgrade: bool, pre: bool) -> ...:
        """
        安装 CLI 扩展
        """
        ...
    def _install_custom(self: object, upgrade: bool, pre: bool) -> ...:
        """
        自定义安装
        """
        ...
