# type: ignore
#
# Auto-generated type stub for list.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
List 命令实现

列出已安装的组件
"""

import asyncio
from argparse import ArgumentParser
from rich.table import Table
from rich.box import SIMPLE
from ..utils import PackageManager
from ..console import console
from ..base import Command

class ListCommand(Command):
    def __init__(self: None) -> ...:
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        ...
    def execute(self: object, args: ...) -> ...:
        ...
    def _print_installed_packages(self: object, pkg_type: str, outdated_only: bool = ...) -> ...:
        """
        打印已安装包信息
        
        :param pkg_type: 包类型 (modules/adapters/cli)
        :param outdated_only: 是否只显示可升级的包
        """
        ...
    def _is_package_outdated(self: object, package_name: str, current_version: str) -> bool:
        """
        检查包是否过时
        
        :param package_name: 包名
        :param current_version: 当前版本
        :return: 是否有新版本可用
        """
        ...
