# type: ignore
#
# Auto-generated type stub for self_update.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Self-Update 命令实现

更新 ErisPulse SDK 本身
"""

import sys
import asyncio
from argparse import ArgumentParser
from rich.prompt import Confirm, Prompt
from rich.panel import Panel
from ..utils import PackageManager
from ..console import console
from ..base import Command

class SelfUpdateCommand(Command):
    def __init__(self: None) -> ...:
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        ...
    def execute(self: object, args: ...) -> ...:
        ...
    def _select_target_version(self: object, versions: ..., specified_version: str = ..., include_pre: bool = ...) -> str:
        """
        选择目标版本
        
        :param versions: 版本列表
        :param specified_version: 用户指定的版本
        :param include_pre: 是否包含预发布版本
        :return: 目标版本号
        """
        ...
    def _select_from_version_list(self: object, versions: ..., include_pre: bool = ...) -> str:
        """
        从版本列表中选择
        
        :param versions: 版本列表
        :param include_pre: 是否包含预发布版本
        :return: 选中的版本号
        """
        ...
