# type: ignore
#
# Auto-generated type stub for uninstall.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Uninstall 命令实现

支持卸载模块、适配器、CLI 扩展
"""

import sys
from argparse import ArgumentParser
from ..utils import PackageManager
from ..base import Command

class UninstallCommand(Command):
    def __init__(self: None) -> ...:
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        ...
    def execute(self: object, args: ...) -> ...:
        ...
