# type: ignore
#
# Auto-generated type stub for upgrade.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Upgrade 命令实现

升级组件
"""

import sys
from argparse import ArgumentParser
from rich.prompt import Confirm
from ..utils import PackageManager
from ..base import Command

class UpgradeCommand(Command):
    def __init__(self: None) -> ...:
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        ...
    def execute(self: object, args: ...) -> ...:
        ...
