name = "get-erispulse"
main = "src/index.ts"
compatibility_date = "2025-04-01"

routes = [
  { pattern = "get.erisdev.com/install.ps1", zone_name = "erisdev.com" },
  { pattern = "get.erisdev.com/install.sh", zone_name = "erisdev.com" },
]

[vars]
GITHUB_REPO = "ErisPulse/ErisPulse"
GITHUB_BRANCH = "Develop/v2"
CACHE_TTL = 300
