# type: ignore
#
# Auto-generated type stub for cli.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

import argparse
import importlib.metadata
import sys
import os
import time
import asyncio
from typing import List, Dict, Optional, Any
from watchdog.observers import Observer
from rich.panel import Panel
from rich.table import Table
from rich.prompt import Confirm, Prompt
from rich.box import SIMPLE
from .console import console

class CLI:
    """
    ErisPulse命令行接口
    
    提供完整的命令行交互功能
    
    {!--< tips >!--}
    1. 支持动态加载第三方命令
    2. 支持模块化子命令系统
    {!--< /tips >!--}
    """
    def __init__(self: None) -> ...:
        """
        初始化CLI
        """
        ...
    def _create_parser(self: object) -> argparse.ArgumentParser:
        """
        创建命令行参数解析器
        
        :return: 配置好的ArgumentParser实例
        """
        ...
    def _get_external_commands(self: object) -> List[str]:
        """
        获取所有已注册的第三方命令名称
        
        :return: 第三方命令名称列表
        """
        ...
    def _load_external_commands(self: object, subparsers: ...) -> ...:
        """
        加载第三方CLI命令
        
        :param subparsers: 子命令解析器
        
        :raises ImportError: 加载命令失败时抛出
        """
        ...
    def _print_version(self: object) -> ...:
        """
        打印版本信息
        """
        ...
    def _print_installed_packages(self: object, pkg_type: str, outdated_only: bool = ...) -> ...:
        """
        打印已安装包信息
        
        :param pkg_type: 包类型 (modules/adapters/cli/all)
        :param outdated_only: 是否只显示可升级的包
        """
        ...
    def _print_remote_packages(self: object, pkg_type: str) -> ...:
        """
        打印远程包信息
        
        :param pkg_type: 包类型 (modules/adapters/cli/all)
        """
        ...
    def _is_package_outdated(self: object, package_name: str, current_version: str) -> bool:
        """
        检查包是否过时
        
        :param package_name: 包名
        :param current_version: 当前版本
        :return: 是否有新版本可用
        """
        ...
    def _resolve_package_name(self: object, short_name: str) -> Optional[str]:
        """
        解析简称到完整包名（大小写不敏感）
        
        :param short_name: 模块/适配器简称
        :return: 完整包名，未找到返回None
        """
        ...
    def _print_search_results(self: object, query: str, results: Dict[(str, List[Dict[(str, str)]])]) -> ...:
        """
        打印搜索结果
        
        :param query: 搜索关键词
        :param results: 搜索结果
        """
        ...
    def _print_version_list(self: object, versions: List[Dict[(str, Any)]], include_pre: bool = ...) -> ...:
        """
        打印版本列表
        
        :param versions: 版本信息列表
        :param include_pre: 是否包含预发布版本
        """
        ...
    def _setup_watchdog(self: object, script_path: str, reload_mode: bool) -> ...:
        """
        设置文件监控
        
        :param script_path: 要监控的脚本路径
        :param reload_mode: 是否启用重载模式
        """
        ...
    def _cleanup(self: object) -> ...:
        """
        清理资源
        """
        ...
    def run(self: object) -> ...:
        """
        运行CLI
        
        :raises KeyboardInterrupt: 用户中断时抛出
        :raises Exception: 命令执行失败时抛出
        """
        ...

def _cleanup_adapters() -> ...:
    """
    清理适配器资源
    """
    ...

def _cleanup_modules() -> ...:
    """
    清理模块资源
    """
    ...
