# type: ignore
#
# Auto-generated type stub for __init__.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
命令模块

导出所有可用的 CLI 命令
"""

from .install import InstallCommand
from .uninstall import UninstallCommand
from .list import ListCommand
from .list_remote import ListRemoteCommand
from .upgrade import UpgradeCommand
from .self_update import SelfUpdateCommand
from .run import RunCommand
from .init import InitCommand
