# type: ignore
#
# Auto-generated type stub for adapter.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Adapter 命令实现

支持启用和禁用适配器
"""

import sys
from argparse import ArgumentParser
from ...package_manager import PackageManager
from ...console import console
from ..base import Command

class AdapterCommand(Command):
    """
    适配器管理命令
    """
    def __init__(self: None) -> ...:
        """
        初始化命令
        """
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        """
        添加命令参数
        """
        ...
    def execute(self: object, args: ...) -> ...:
        """
        执行命令
        """
        ...
    def _list_adapters(self: object, installed: ..., show_all: bool) -> ...:
        """
        列出适配器状态
        
        :param installed: 已安装的包信息
        :param show_all: 是否显示所有适配器
        """
        ...
