# type: ignore
#
# Auto-generated type stub for init.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Init 命令实现

交互式初始化 ErisPulse 项目
"""

import os
import asyncio
import concurrent.futures
import subprocess
import sys
from argparse import ArgumentParser
from pathlib import Path
from rich.prompt import Confirm, Prompt
from ...console import console
from ...package_manager import PackageManager
from ..base import Command

class InitCommand(Command):
    """
    初始化命令
    """
    def __init__(self: None) -> ...:
        """
        初始化命令
        """
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        """
        添加命令参数
        """
        ...
    def execute(self: object, args: ...) -> ...:
        """
        执行命令
        """
        ...
    def _init_project(self: object, project_name: str, adapter_list: list = ...) -> bool:
        """
        初始化新项目
        
        :param project_name: 项目名称
        :param adapter_list: 需要初始化的适配器列表
        :return: 是否初始化成功
        """
        ...
    async def _fetch_available_adapters(self: object) -> ...:
        """
        从云端获取可用适配器列表
        
        :return: 适配器名称到描述的映射
        """
        ...
    def _configure_adapters_interactive_sync(self: object, project_path: str = ...) -> ...:
        """
        交互式配置适配器的同步版本
        
        :param project_path: 项目路径
        """
        ...
    def _install_adapters(self: object, adapter_names: ..., adapters_info: ...) -> ...:
        """
        安装选中的适配器
        
        :param adapter_names: 适配器名称列表
        :param adapters_info: 适配器信息字典
        """
        ...
    def _interactive_init(self: object, project_name: str = ..., force: bool = ...) -> bool:
        """
        交互式初始化项目
        
        :param project_name: 项目名称
        :param force: 是否强制覆盖
        :return: 是否初始化成功
        """
        ...
