# type: ignore
#
# Auto-generated type stub for list_remote.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
List-Remote 命令实现

列出远程可用的组件
"""

import asyncio
from argparse import ArgumentParser
from rich.table import Table
from rich.box import SIMPLE
from ...package_manager import PackageManager
from ...console import console
from ..base import Command

class ListRemoteCommand(Command):
    """
    远程列表命令
    """
    def __init__(self: None) -> ...:
        """
        初始化命令
        """
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        """
        添加命令参数
        """
        ...
    def execute(self: object, args: ...) -> ...:
        """
        执行命令
        """
        ...
    def _print_remote_packages(self: object, pkg_type: str, force_refresh: bool = ...) -> ...:
        """
        打印远程包信息
        
        :param pkg_type: 包类型 (modules/adapters/cli)
        :param force_refresh: 是否强制刷新缓存
        """
        ...
