# type: ignore
#
# Auto-generated type stub for module.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Module 命令实现

支持启用和禁用模块
"""

import sys
from argparse import ArgumentParser
from ...package_manager import PackageManager
from ...console import console
from ..base import Command

class ModuleCommand(Command):
    """
    模块管理命令
    """
    def __init__(self: None) -> ...:
        """
        初始化命令
        """
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        """
        添加命令参数
        """
        ...
    def execute(self: object, args: ...) -> ...:
        """
        执行命令
        """
        ...
