# type: ignore
#
# Auto-generated type stub for run.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Run 命令实现

运行主程序
"""

import os
import sys
import time
from argparse import ArgumentParser
from watchdog.observers import Observer
from rich.panel import Panel
from ...console import console
from ...reload_handler import ReloadHandler
from ..base import Command

class RunCommand(Command):
    """
    运行命令
    """
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        """
        添加命令参数
        """
        ...
    def execute(self: object, args: ...) -> ...:
        """
        执行命令
        """
        ...
    def _setup_watchdog(self: object, script_path: str, reload_mode: bool) -> ...:
        """
        设置文件监控
        
        :param script_path: 要监控的脚本路径
        :param reload_mode: 是否启用重载模式
        """
        ...
    def _cleanup(self: object) -> ...:
        """
        清理资源
        """
        ...
