# type: ignore
#
# Auto-generated type stub for uninstall.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Uninstall 命令实现

支持卸载模块、适配器、CLI 扩展
"""

import sys
from argparse import ArgumentParser
from ...package_manager import PackageManager
from ...console import console
from ..base import Command

class UninstallCommand(Command):
    """
    卸载命令
    """
    def __init__(self: None) -> ...:
        """
        初始化命令
        """
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        """
        添加命令参数
        """
        ...
    def execute(self: object, args: ...) -> ...:
        """
        执行命令
        """
        ...
