# type: ignore
#
# Auto-generated type stub for upgrade.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
Upgrade 命令实现

升级组件
"""

import sys
from argparse import ArgumentParser
from rich.prompt import Confirm
from ...package_manager import PackageManager
from ...console import console
from ..base import Command

class UpgradeCommand(Command):
    """
    升级命令
    """
    def __init__(self: None) -> ...:
        """
        初始化命令
        """
        ...
    def add_arguments(self: object, parser: ArgumentParser) -> ...:
        """
        添加命令参数
        """
        ...
    def execute(self: object, args: ...) -> ...:
        """
        执行命令
        """
        ...
