# type: ignore
#
# Auto-generated type stub for _self_config.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 框架配置管理

专门管理 ErisPulse 框架自身的配置项。
"""

from typing import Dict, Any
from .config import config

def _ensure_erispulse_config_structure(config_dict: Dict[(str, Any)]) -> Dict[(str, Any)]:
    """
    确保 ErisPulse 配置结构完整，补全缺失的配置项
    
    :param config_dict: 当前配置
    :return: 补全后的完整配置
    """
    ...

def get_erispulse_config() -> Dict[(str, Any)]:
    """
    获取 ErisPulse 框架配置，自动补全缺失的配置项并保存
    
    :return: 完整的 ErisPulse 配置字典
    """
    ...

def update_erispulse_config(new_config: Dict[(str, Any)]) -> bool:
    """
    更新 ErisPulse 配置，自动补全缺失的配置项
    
    :param new_config: 新的配置字典
    :return: 是否更新成功
    """
    ...

def get_server_config() -> Dict[(str, Any)]:
    """
    获取服务器配置，确保结构完整
    
    :return: 服务器配置字典
    """
    ...

def get_logger_config() -> Dict[(str, Any)]:
    """
    获取日志配置，确保结构完整
    
    :return: 日志配置字典
    """
    ...

def get_storage_config() -> Dict[(str, Any)]:
    """
    获取存储模块配置
    
    :return: 存储配置字典
    """
    ...

def get_framework_config() -> Dict[(str, Any)]:
    """
    获取框架配置
    
    :return: 框架配置字典
    """
    ...
