# type: ignore
#
# Auto-generated type stub for config.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 配置中心

集中管理所有配置项，避免循环导入问题
提供自动补全缺失配置项的功能
添加内存缓存和延迟写入机制以提高性能
"""

import os
import time
import toml
import threading
from typing import Any, Dict

class ConfigManager:
    def __init__(self: None, config_file: str = ...) -> ...:
        ...
    def _load_config(self: object) -> None:
        """
        从文件加载配置到缓存
        """
        ...
    def _flush_config(self: object) -> None:
        """
        将待写入的配置刷新到文件
        """
        ...
    def _schedule_write(self: object) -> None:
        """
        安排延迟写入
        """
        ...
    def _check_cache_validity(self: object) -> None:
        """
        检查缓存有效性，必要时重新加载
        """
        ...
    def getConfig(self: object, key: str, default: Any = ...) -> Any:
        """
        获取模块/适配器配置项（优先从缓存获取）
        :param key: 配置项的键(支持点分隔符如"module.sub.key")
        :param default: 默认值
        :return: 配置项的值
        """
        ...
    def setConfig(self: object, key: str, value: Any, immediate: bool = ...) -> bool:
        """
        设置模块/适配器配置（缓存+延迟写入）
        :param key: 配置项键名(支持点分隔符如"module.sub.key")
        :param value: 配置项值
        :param immediate: 是否立即写入磁盘（默认为False，延迟写入）
        :return: 操作是否成功
        """
        ...
    def force_save(self: object) -> None:
        """
        强制立即保存所有待写入的配置到磁盘
        """
        ...
    def reload(self: object) -> None:
        """
        重新从磁盘加载配置，丢弃所有未保存的更改
        """
        ...
