# type: ignore
#
# Auto-generated type stub for exceptions.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 全局异常处理系统

提供统一的异常捕获和格式化功能，支持同步和异步代码的异常处理。
"""

import sys
import traceback
import asyncio
import os
from typing import Dict, Any, Type

class ExceptionHandler:
    def format_exception(exc_type: Type[Exception], exc_value: Exception, exc_traceback: Any) -> str:
        """
        :param exc_type: 异常类型
        :param exc_value: 异常值
        :param exc_traceback: 追踪信息
        :return: 格式化后的异常信息
        """
        ...
    def format_async_exception(exception: Exception) -> str:
        """
        :param exception: 异常对象
        :return: 格式化后的异常信息
        """
        ...

def global_exception_handler(exc_type: Type[Exception], exc_value: Exception, exc_traceback: Any) -> None:
    """
    全局异常处理器
    
    :param exc_type: 异常类型
    :param exc_value: 异常值
    :param exc_traceback: 追踪信息
    """
    ...

def async_exception_handler(loop: asyncio.AbstractEventLoop, context: Dict[(str, Any)]) -> None:
    """
    异步异常处理器
    
    :param loop: 事件循环
    :param context: 上下文字典
    """
    ...

def setup_async_loop(loop: asyncio.AbstractEventLoop = ...) -> None:
    """
    为指定的事件循环设置异常处理器
    
    :param loop: 事件循环实例，如果为None则使用当前事件循环
    """
    ...
