# type: ignore
#
# Auto-generated type stub for lifecycle.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 生命周期管理模块

提供统一的生命周期事件管理和触发机制

事件标准格式:
{
    "event": "事件名称",  # 必填
    "timestamp": float,  # 必填，Unix时间戳
    "data": dict,        # 可选，事件相关数据
    "source": str,       # 必填，事件来源
    "msg": str           # 可选，事件描述
}
"""

import asyncio
import time
from typing import Callable, List, Dict, Any
from .logger import logger

class LifecycleManager:
    """
    生命周期管理器
    
    管理SDK的生命周期事件，提供事件注册和触发功能
    支持点式结构事件监听，例如 module.init 可以被 module 监听到
    """
    def __init__(self: None) -> ...:
        ...
    def _validate_event(self: object, event_data: Dict[(str, Any)]) -> bool:
        """
        验证事件数据格式
        
        :param event_data: 事件数据字典
        :return: 是否有效
        """
        ...
    def on(self: object, event: str) -> Callable:
        """
        注册生命周期事件处理器
        
        :param event: 事件名称，支持点式结构如 module.init
        :return: 装饰器函数
        
        :raises ValueError: 当事件名无效时抛出
        """
        ...
    def start_timer(self: object, timer_id: str) -> None:
        """
        开始计时
        
        :param timer_id: 计时器ID
        """
        ...
    def get_duration(self: object, timer_id: str) -> float:
        """
        获取指定计时器的持续时间
        
        :param timer_id: 计时器ID
        :return: 持续时间(秒)
        """
        ...
    def stop_timer(self: object, timer_id: str) -> float:
        """
        停止计时并返回持续时间
        
        :param timer_id: 计时器ID
        :return: 持续时间(秒)
        """
        ...
    async def submit_event(self: object, event_type: str) -> None:
        """
        提交生命周期事件
        
        :param event: 事件名称
        :param event_data: 事件数据字典
        """
        ...
    async def _execute_handlers(self: object, event: str, event_data: Dict[(str, Any)]) -> None:
        """
        执行事件处理器
        
        :param event: 事件名称
        :param event_data: 事件数据
        """
        ...
