# type: ignore
#
# Auto-generated type stub for storage.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 存储管理模块

提供键值存储、事务支持、快照和恢复功能，用于管理框架运行时数据。
基于SQLite实现持久化存储，支持复杂数据类型和原子操作。

支持两种数据库模式：
1. 项目数据库（默认）：位于项目目录下的 config/config.db
2. 全局数据库：位于包内的 ../data/config.db

用户可通过在 config.toml 中配置以下选项来选择使用全局数据库：
```toml
[ErisPulse.storage]
use_global_db = true
```

{!--< tips >!--}
1. 支持JSON序列化存储复杂数据类型
2. 提供事务支持确保数据一致性
3. 自动快照功能防止数据丢失
{!--< /tips >!--}
"""

import os
import json
import sqlite3
import shutil
import time
from datetime import datetime
from typing import List, Dict, Optional, Any, Tuple, Type

class StorageManager:
    """
    存储管理器
    
    单例模式实现，提供键值存储的增删改查、事务和快照管理
    
    支持两种数据库模式：
    1. 项目数据库（默认）：位于项目目录下的 config/config.db
    2. 全局数据库：位于包内的 ../data/config.db
    
    用户可通过在 config.toml 中配置以下选项来选择使用全局数据库：
    ```toml
    [ErisPulse.storage]
    use_global_db = true
    ```
    
    {!--< tips >!--}
    1. 使用get/set方法操作存储项
    2. 使用transaction上下文管理事务
    3. 使用snapshot/restore管理数据快照
    {!--< /tips >!--}
    """
    def __new__(cls: object, *args: ..., **kwargs: ...) -> ...:
        ...
    def __init__(self: None) -> ...:
        ...
    def _ensure_directories(self: object) -> None:
        """
        确保必要的目录存在
        """
        ...
    def get(self: object, key: str, default: Any = ...) -> Any:
        """
        获取存储项的值
        
        :param key: 存储项键名
        :param default: 默认值(当键不存在时返回)
        :return: 存储项的值
        
        :example:
        >>> timeout = storage.get("network.timeout", 30)
        >>> user_settings = storage.get("user.settings", {})
        """
        ...
    def get_all_keys(self: object) -> List[str]:
        """
        获取所有存储项的键名
        
        :return: 键名列表
        
        :example:
        >>> all_keys = storage.get_all_keys()
        >>> print(f"共有 {len(all_keys)} 个存储项")
        """
        ...
    def set(self: object, key: str, value: Any) -> bool:
        """
        设置存储项的值
        
        :param key: 存储项键名
        :param value: 存储项的值
        :return: 操作是否成功
        
        :example:
        >>> storage.set("app.name", "MyApp")
        >>> storage.set("user.settings", {"theme": "dark"})
        """
        ...
    def set_multi(self: object, items: Dict[(str, Any)]) -> bool:
        """
        批量设置多个存储项
        
        :param items: 键值对字典
        :return: 操作是否成功
        
        :example:
        >>> storage.set_multi({
        >>>     "app.name": "MyApp",
        >>>     "app.version": "1.0.0",
        >>>     "app.debug": True
        >>> })
        """
        ...
    def getConfig(self: object, key: str, default: Any = ...) -> Any:
        """
        获取模块/适配器配置项（委托给config模块）
        :param key: 配置项的键(支持点分隔符如"module.sub.key")
        :param default: 默认值
        :return: 配置项的值
        """
        ...
    def setConfig(self: object, key: str, value: Any) -> bool:
        """
        设置模块/适配器配置（委托给config模块）
        :param key: 配置项键名(支持点分隔符如"module.sub.key")
        :param value: 配置项值
        :return: 操作是否成功
        """
        ...
    def delete(self: object, key: str) -> bool:
        """
        删除存储项
        
        :param key: 存储项键名
        :return: 操作是否成功
        
        :example:
        >>> storage.delete("temp.session")
        """
        ...
    def delete_multi(self: object, keys: List[str]) -> bool:
        """
        批量删除多个存储项
        
        :param keys: 键名列表
        :return: 操作是否成功
        
        :example:
        >>> storage.delete_multi(["temp.key1", "temp.key2"])
        """
        ...
    def get_multi(self: object, keys: List[str]) -> Dict[(str, Any)]:
        """
        批量获取多个存储项的值
        
        :param keys: 键名列表
        :return: 键值对字典
        
        :example:
        >>> settings = storage.get_multi(["app.name", "app.version"])
        """
        ...
    def transaction(self: object) -> StorageManager._Transaction:
        """
        创建事务上下文
        
        :return: 事务上下文管理器
        
        :example:
        >>> with storage.transaction():
        >>>     storage.set("key1", "value1")
        >>>     storage.set("key2", "value2")
        """
        ...
    def set_snapshot_interval(self: object, seconds: int) -> None:
        """
        设置自动快照间隔
        
        :param seconds: 间隔秒数
        
        :example:
        >>> # 每30分钟自动快照
        >>> storage.set_snapshot_interval(1800)
        """
        ...
    def clear(self: object) -> bool:
        """
        清空所有存储项
        
        :return: 操作是否成功
        
        :example:
        >>> storage.clear()  # 清空所有存储
        """
        ...
    def __getattr__(self: object, key: str) -> Any:
        """
        通过属性访问存储项
        
        :param key: 存储项键名
        :return: 存储项的值
        
        :raises AttributeError: 当存储项不存在时抛出
            
        :example:
        >>> app_name = storage.app_name
        """
        ...
    def __setattr__(self: object, key: str, value: Any) -> None:
        """
        通过属性设置存储项
        
        :param key: 存储项键名
        :param value: 存储项的值
            
        :example:
        >>> storage.app_name = "MyApp"
        """
        ...
    def snapshot(self: object, name: Optional[str] = ...) -> str:
        """
        创建数据库快照
        
        :param name: 快照名称(可选)
        :return: 快照文件路径
        
        :example:
        >>> # 创建命名快照
        >>> snapshot_path = storage.snapshot("before_update")
        >>> # 创建时间戳快照
        >>> snapshot_path = storage.snapshot()
        """
        ...
    def restore(self: object, snapshot_name: str) -> bool:
        """
        从快照恢复数据库
        
        :param snapshot_name: 快照名称或路径
        :return: 恢复是否成功
        
        :example:
        >>> storage.restore("before_update")
        """
        ...
    def list_snapshots(self: object) -> List[Tuple[(str, datetime, int)]]:
        """
        列出所有可用的快照
        
        :return: 快照信息列表(名称, 创建时间, 大小)
        
        :example:
        >>> for name, date, size in storage.list_snapshots():
        >>>     print(f"{name} - {date} ({size} bytes)")
        """
        ...
    def delete_snapshot(self: object, snapshot_name: str) -> bool:
        """
        删除指定的快照
        
        :param snapshot_name: 快照名称
        :return: 删除是否成功
        
        :example:
        >>> storage.delete_snapshot("old_backup")
        """
        ...
