# type: ignore
#
# Auto-generated type stub for __init__.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 基础模块

提供核心基类定义，包括适配器和模块基类
"""

from .adapter import SendDSL, BaseAdapter
from .module import BaseModule
