# type: ignore
#
# Auto-generated type stub for base.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 事件处理基础模块

提供事件处理的核心功能，包括事件注册和处理

{!--< tips >!--}
1. 所有事件处理都基于OneBot12标准事件格式
2. 通过适配器系统进行事件分发和接收
{!--< /tips >!--}
"""

from .. import adapter, logger
from typing import Callable, Any, Dict, List
import asyncio
from .wrapper import Event

class BaseEventHandler:
    """
    基础事件处理器
    
    提供事件处理的基本功能，包括处理器注册和注销
    """
    def __init__(self: None, event_type: str, module_name: str = ...) -> ...:
        """
        初始化事件处理器
        
        :param event_type: 事件类型
        :param module_name: 模块名称
        """
        ...
    def register(self: object, handler: Callable, priority: int = ..., condition: Callable = ...) -> ...:
        """
        注册事件处理器
        
        :param handler: 事件处理器函数
        :param priority: 处理器优先级，数值越小优先级越高
        :param condition: 处理器条件函数，返回True时才会执行处理器
        """
        ...
    def unregister(self: object, handler: Callable) -> bool:
        """
        注销事件处理器
        
        :param handler: 要注销的事件处理器
        :return: 是否成功注销
        """
        ...
    def __call__(self: object, priority: int = ..., condition: Callable = ...) -> ...:
        """
        装饰器方式注册事件处理器
        
        :param priority: 处理器优先级
        :param condition: 处理器条件函数
        :return: 装饰器函数
        """
        ...
