# type: ignore
#
# Auto-generated type stub for meta.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 元事件处理模块

提供基于装饰器的元事件处理功能

{!--< tips >!--}
1. 支持连接、断开连接等生命周期事件
2. 适用于系统状态监控和初始化操作
{!--< /tips >!--}
"""

from .base import BaseEventHandler
from typing import Callable, Dict, Any

class MetaHandler:
    """
    元事件处理器
    
    提供元事件处理功能，如连接、断开连接等
    """
    def __init__(self: None) -> ...:
        ...
    def on_meta(self: object, priority: int = ...) -> ...:
        """
        通用元事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_meta_handler(self: object, handler: Callable) -> bool:
        """
        取消注册通用元事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_connect(self: object, priority: int = ...) -> ...:
        """
        连接事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_connect_handler(self: object, handler: Callable) -> bool:
        """
        取消注册连接事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_disconnect(self: object, priority: int = ...) -> ...:
        """
        断开连接事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_disconnect_handler(self: object, handler: Callable) -> bool:
        """
        取消注册断开连接事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_heartbeat(self: object, priority: int = ...) -> ...:
        """
        心跳事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_heartbeat_handler(self: object, handler: Callable) -> bool:
        """
        取消注册心跳事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
