# type: ignore
#
# Auto-generated type stub for request.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 请求处理模块

提供基于装饰器的请求事件处理功能

{!--< tips >!--}
1. 支持好友请求、群邀请等不同类型请求
2. 可以通过返回特定值来同意或拒绝请求
{!--< /tips >!--}
"""

from .base import BaseEventHandler
from typing import Callable, Dict, Any

class RequestHandler:
    """
    请求事件处理器
    
    提供请求事件处理功能
    """
    def __init__(self: None) -> ...:
        ...
    def on_request(self: object, priority: int = ...) -> ...:
        """
        通用请求事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_request_handler(self: object, handler: Callable) -> bool:
        """
        取消注册通用请求事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_friend_request(self: object, priority: int = ...) -> ...:
        """
        好友请求事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_friend_request_handler(self: object, handler: Callable) -> bool:
        """
        取消注册好友请求事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
    def on_group_request(self: object, priority: int = ...) -> ...:
        """
        群邀请请求事件装饰器
        
        :param priority: 处理器优先级
        :return: 装饰器函数
        """
        ...
    def remove_group_request_handler(self: object, handler: Callable) -> bool:
        """
        取消注册群邀请请求事件处理器
        
        :param handler: 要取消注册的处理器
        :return: 是否成功取消注册
        """
        ...
