# type: ignore
#
# Auto-generated type stub for wrapper.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse 事件包装类

提供便捷的事件访问方法

{!--< tips >!--}
1. 继承自dict，完全兼容字典访问
2. 提供便捷方法简化事件处理
3. 支持点式访问 event.platform
{!--< /tips >!--}
"""

from typing import Any, Dict, List, Optional, Callable, Awaitable, Union
from .. import adapter, logger
import asyncio

class Event(dict):
    """
    事件包装类
    
    提供便捷的事件访问方法
    
    {!--< tips >!--}
    所有方法都是可选的，不影响原有字典访问方式
    {!--< /tips >!--}
    """
    def __init__(self: None, event_data: Dict[(str, Any)]) -> ...:
        """
        初始化事件包装器
        
        :param event_data: 原始事件数据
        """
        ...
    def get_id(self: object) -> str:
        """
        获取事件ID
        
        :return: 事件ID
        """
        ...
    def get_time(self: object) -> int:
        """
        获取事件时间戳
        
        :return: Unix时间戳（秒级）
        """
        ...
    def get_type(self: object) -> str:
        """
        获取事件类型
        
        :return: 事件类型（message/notice/request/meta等）
        """
        ...
    def get_detail_type(self: object) -> str:
        """
        获取事件详细类型
        
        :return: 事件详细类型（private/group/friend等）
        """
        ...
    def get_platform(self: object) -> str:
        """
        获取平台名称
        
        :return: 平台名称
        """
        ...
    def get_self_platform(self: object) -> str:
        """
        获取机器人平台
        
        :return: 机器人平台名称
        """
        ...
    def get_self_user_id(self: object) -> str:
        """
        获取机器人用户ID
        
        :return: 机器人用户ID
        """
        ...
    def get_self_info(self: object) -> Dict[(str, Any)]:
        """
        获取机器人完整信息
        
        :return: 机器人信息字典
        """
        ...
    def get_message(self: object) -> List[Dict[(str, Any)]]:
        """
        获取消息段数组
        
        :return: 消息段数组
        """
        ...
    def get_alt_message(self: object) -> str:
        """
        获取消息备用文本
        
        :return: 消息备用文本
        """
        ...
    def get_text(self: object) -> str:
        """
        获取纯文本内容
        
        :return: 纯文本内容
        """
        ...
    def get_message_text(self: object) -> str:
        """
        获取纯文本内容（别名）
        
        :return: 纯文本内容
        """
        ...
    def has_mention(self: object) -> bool:
        """
        是否包含@消息
        
        :return: 是否包含@消息
        """
        ...
    def get_mentions(self: object) -> List[str]:
        """
        获取所有被@的用户ID列表
        
        :return: 被@的用户ID列表
        """
        ...
    def get_user_id(self: object) -> str:
        """
        获取发送者ID
        
        :return: 发送者用户ID
        """
        ...
    def get_user_nickname(self: object) -> str:
        """
        获取发送者昵称
        
        :return: 发送者昵称
        """
        ...
    def get_group_id(self: object) -> str:
        """
        获取群组ID
        
        :return: 群组ID（群聊消息）
        """
        ...
    def get_sender(self: object) -> Dict[(str, Any)]:
        """
        获取发送者信息字典
        
        :return: 发送者信息字典
        """
        ...
    def is_message(self: object) -> bool:
        """
        是否为消息事件
        
        :return: 是否为消息事件
        """
        ...
    def is_private_message(self: object) -> bool:
        """
        是否为私聊消息
        
        :return: 是否为私聊消息
        """
        ...
    def is_group_message(self: object) -> bool:
        """
        是否为群聊消息
        
        :return: 是否为群聊消息
        """
        ...
    def is_at_message(self: object) -> bool:
        """
        是否为@消息
        
        :return: 是否为@消息
        """
        ...
    def get_operator_id(self: object) -> str:
        """
        获取操作者ID
        
        :return: 操作者ID
        """
        ...
    def get_operator_nickname(self: object) -> str:
        """
        获取操作者昵称
        
        :return: 操作者昵称
        """
        ...
    def is_notice(self: object) -> bool:
        """
        是否为通知事件
        
        :return: 是否为通知事件
        """
        ...
    def is_group_member_increase(self: object) -> bool:
        """
        群成员增加
        
        :return: 是否为群成员增加事件
        """
        ...
    def is_group_member_decrease(self: object) -> bool:
        """
        群成员减少
        
        :return: 是否为群成员减少事件
        """
        ...
    def is_friend_add(self: object) -> bool:
        """
        好友添加
        
        :return: 是否为好友添加事件
        """
        ...
    def is_friend_delete(self: object) -> bool:
        """
        好友删除
        
        :return: 是否为好友删除事件
        """
        ...
    def get_comment(self: object) -> str:
        """
        获取请求附言
        
        :return: 请求附言
        """
        ...
    def is_request(self: object) -> bool:
        """
        是否为请求事件
        
        :return: 是否为请求事件
        """
        ...
    def is_friend_request(self: object) -> bool:
        """
        是否为好友请求
        
        :return: 是否为好友请求
        """
        ...
    def is_group_request(self: object) -> bool:
        """
        是否为群组请求
        
        :return: 是否为群组请求
        """
        ...
    def _get_adapter_and_target(self: object) -> tuple:
        """
        获取适配器实例和目标信息
        
        :return: (适配器实例, 详细类型, 目标ID)
        """
        ...
    async def reply(self: object, content: str, method: str = ..., **kwargs: ...) -> Any:
        """
        通用回复方法
        
        基于适配器的Text方法，但可以通过method参数指定其他发送方法
        
        :param content: 发送内容（文本、URL等，取决于method参数）
        :param method: 适配器发送方法，默认为"Text"
                       可选值: "Text", "Image", "Voice", "Video", "File" 等
        :param kwargs: 额外参数，例如Mention方法的user_id
        :return: 适配器发送方法的返回值
        
        :example:
        >>> await event.reply("你好")  # 发送文本
        >>> await event.reply("http://example.com/image.jpg", method="Image")  # 发送图片
        >>> await event.reply("回复内容", method="Mention", user_id="123456")  # @用户并发送
        >>> await event.reply("http://example.com/voice.mp3", method="Voice")  # 发送语音
        """
        ...
    async def forward_to_group(self: object, group_id: str) -> ...:
        """
        转发到群组
        
        :param group_id: 目标群组ID
        """
        ...
    async def forward_to_user(self: object, user_id: str) -> ...:
        """
        转发给用户
        
        :param user_id: 目标用户ID
        """
        ...
    async def wait_reply(self: object, prompt: str = ..., timeout: float = ..., callback: Callable[([Dict[(str, Any)]], Awaitable[Any])] = ..., validator: Callable[([Dict[(str, Any)]], bool)] = ...) -> Optional[Event]:
        """
        等待用户回复
        
        :param prompt: 提示消息，如果提供会发送给用户
        :param timeout: 等待超时时间(秒)
        :param callback: 回调函数，当收到回复时执行
        :param validator: 验证函数，用于验证回复是否有效
        :return: 用户回复的事件数据，如果超时则返回None
        """
        ...
    def get_raw(self: object) -> Dict[(str, Any)]:
        """
        获取原始事件数据
        
        :return: 原始事件数据
        """
        ...
    def get_raw_type(self: object) -> str:
        """
        获取原始事件类型
        
        :return: 原始事件类型
        """
        ...
    def get_command_name(self: object) -> str:
        """
        获取命令名称
        
        :return: 命令名称
        """
        ...
    def get_command_args(self: object) -> List[str]:
        """
        获取命令参数
        
        :return: 命令参数列表
        """
        ...
    def get_command_raw(self: object) -> str:
        """
        获取命令原始文本
        
        :return: 命令原始文本
        """
        ...
    def get_command_info(self: object) -> Dict[(str, Any)]:
        """
        获取完整命令信息
        
        :return: 命令信息字典
        """
        ...
    def is_command(self: object) -> bool:
        """
        是否为命令
        
        :return: 是否为命令
        """
        ...
    def to_dict(self: object) -> Dict[(str, Any)]:
        """
        转换为字典
        
        :return: 事件数据字典
        """
        ...
    def is_processed(self: object) -> bool:
        """
        是否已被处理
        
        :return: 是否已被处理
        """
        ...
    def mark_processed(self: object) -> ...:
        """
        标记为已处理
        """
        ...
    def __getattr__(self: object, name: str) -> Any:
        """
        支持点式访问字典键
        
        :param name: 属性名
        :return: 属性值
        """
        ...
    def __repr__(self: object) -> str:
        """
        字符串表示
        
        :return: 字符串表示
        """
        ...
