# type: ignore
#
# Auto-generated type stub for package_manager.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
ErisPulse SDK 包管理器

提供包安装、卸载、升级和查询功能
"""

import os
import asyncio
import importlib.metadata
import json
import subprocess
import sys
import time
from typing import List, Dict, Tuple, Optional, Any
from rich.panel import Panel
from rich.progress import Progress, BarColumn, TextColumn
from rich.prompt import Confirm
from ..console import console

class PackageManager:
    """
    ErisPulse包管理器
    
    提供包安装、卸载、升级和查询功能
    
    {!--< tips >!--}
    1. 支持本地和远程包管理
    2. 包含1小时缓存机制
    {!--< /tips >!--}
    """
    def __init__(self: None) -> ...:
        """
        初始化包管理器
        """
        ...
    async def _fetch_remote_packages(self: object, url: str) -> Optional[dict]:
        """
        从指定URL获取远程包数据
        
        :param url: 远程包数据URL
        :return: 解析后的JSON数据，失败返回None
        
        :raises ClientError: 网络请求失败时抛出
        :raises JSONDecodeError: JSON解析失败时抛出
        """
        ...
    async def get_remote_packages(self: object, force_refresh: bool = ...) -> dict:
        """
        获取远程包列表，带缓存机制
        
        :param force_refresh: 是否强制刷新缓存
        :return: 包含模块和适配器的字典
        
        :return:
            dict: {
                "modules": {模块名: 模块信息},
                "adapters": {适配器名: 适配器信息},
                "cli_extensions": {扩展名: 扩展信息}
            }
        """
        ...
    def get_installed_packages(self: object) -> Dict[(str, Dict[(str, Dict[(str, str)])])]:
        """
        获取已安装的包信息
        
        :return: 已安装包字典，包含模块、适配器和CLI扩展
        
        :return:
            dict: {
                "modules": {模块名: 模块信息},
                "adapters": {适配器名: 适配器信息},
                "cli_extensions": {扩展名: 扩展信息}
            }
        """
        ...
    def _is_module_enabled(self: object, module_name: str) -> bool:
        """
        检查模块是否启用
        
        :param module_name: 模块名称
        :return: 模块是否启用
        
        :raises ImportError: 核心模块不可用时抛出
        """
        ...
    def _normalize_name(self: object, name: str) -> str:
        """
        标准化包名，统一转为小写以实现大小写不敏感比较
        
        :param name: 原始名称
        :return: 标准化后的名称
        """
        ...
    async def _find_package_by_alias(self: object, alias: str) -> Optional[str]:
        """
        通过别名查找实际包名（大小写不敏感）
        支持查找已安装包和远程包
        
        :param alias: 包别名或PyPI包名
        :return: 实际包名，未找到返回None
        """
        ...
    def _find_installed_package_by_name(self: object, name: str) -> Optional[str]:
        """
        在已安装包中查找实际包名（大小写不敏感）
        
        :param name: 包名或别名
        :return: 实际包名，未找到返回None
        """
        ...
    async def check_package_updates(self: object) -> Dict[(str, Tuple[(str, str)])]:
        """
        检查包更新，对比本地版本和远程版本
        
        :return: {包名: (当前版本, 最新版本)}，仅包含有新版本的包
        """
        ...
    async def _get_pypi_package_version(self: object, package_name: str, force_refresh: bool = ...) -> Optional[str]:
        """
        从PyPI获取包的最新版本，带缓存机制
        
        :param package_name: PyPI包名
        :param force_refresh: 是否强制刷新缓存
        :return: 最新版本号，失败返回None
        """
        ...
    def _run_pip_command_with_output(self: object, args: List[str], description: str) -> Tuple[(bool, str, str)]:
        """
        执行pip命令并捕获输出
        
        :param args: pip命令参数列表
        :param description: 进度条描述
        :return: (是否成功, 标准输出, 标准错误)
        """
        ...
    def _compare_versions(self: object, version1: str, version2: str) -> int:
        """
        比较两个版本号
        
        :param version1: 版本号1
        :param version2: 版本号2
        :return: 1 if version1 > version2, -1 if version1 < version2, 0 if equal
        """
        ...
    def _check_sdk_compatibility(self: object, min_sdk_version: str) -> Tuple[(bool, str)]:
        """
        检查SDK版本兼容性
        
        :param min_sdk_version: 所需的最小SDK版本
        :return: (是否兼容, 当前版本信息)
        """
        ...
    async def _get_package_info(self: object, package_name: str) -> Optional[Dict[(str, Any)]]:
        """
        获取包的详细信息（包括min_sdk_version等）
        
        :param package_name: 包名或别名
        :return: 包信息字典
        """
        ...
    def install_package(self: object, package_names: List[str], upgrade: bool = ..., pre: bool = ...) -> bool:
        """
        安装指定包（支持多个包）
        
        :param package_names: 要安装的包名或别名列表
        :param upgrade: 是否升级已安装的包
        :param pre: 是否包含预发布版本
        :return: 安装是否成功
        """
        ...
    def uninstall_package(self: object, package_names: List[str]) -> bool:
        """
        卸载指定包（支持多个包，支持别名）
        
        :param package_names: 要卸载的包名或别名列表
        :return: 卸载是否成功
        """
        ...
    def upgrade_all(self: object) -> bool:
        """
        升级所有有新版本的ErisPulse包
        
        :return: 升级是否成功
        
        :raises KeyboardInterrupt: 用户取消操作时抛出
        """
        ...
    def upgrade_package(self: object, package_names: List[str], pre: bool = ...) -> bool:
        """
        升级指定包（支持多个包）
        
        :param package_names: 要升级的包名或别名列表
        :param pre: 是否包含预发布版本
        :return: 升级是否成功
        """
        ...
    def search_package(self: object, query: str) -> Dict[(str, List[Dict[(str, str)]])]:
        """
        搜索包（本地和远程）
        
        :param query: 搜索关键词
        :return: 匹配的包信息
        """
        ...
    def get_installed_version(self: object) -> str:
        """
        获取当前安装的ErisPulse版本
        
        :return: 当前版本号
        """
        ...
    async def get_pypi_versions(self: object) -> List[Dict[(str, Any)]]:
        """
        从PyPI获取ErisPulse的所有可用版本
        
        :return: 版本信息列表
        """
        ...
    def _is_pre_release(self: object, version: str) -> bool:
        """
        判断版本是否为预发布版本
        
        :param version: 版本号
        :return: 是否为预发布版本
        """
        ...
    def update_self(self: object, target_version: str = ..., force: bool = ...) -> bool:
        """
        更新ErisPulse SDK本身
        
        :param target_version: 目标版本号，None表示更新到最新版本
        :param force: 是否强制更新
        :return: 更新是否成功
        """
        ...
