# type: ignore
#
# Auto-generated type stub for __main__.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
主 CLI 类

ErisPulse 命令行接口主入口
"""

import sys
import importlib.metadata
import asyncio
import traceback
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from rich.panel import Panel
from ..console import console
from .registry import CommandRegistry
from .commands import InstallCommand, UninstallCommand, ModuleCommand, AdapterCommand, ListCommand, ListRemoteCommand, UpgradeCommand, SelfUpdateCommand, RunCommand, InitCommand

class CLI:
    """
    ErisPulse 命令行接口主类
    
    提供完整的命令行交互功能，支持动态加载第三方命令
    """
    def __init__(self: None) -> ...:
        """
        初始化 CLI
        """
        ...
    def _create_parser(self: object) -> ArgumentParser:
        """
        创建命令行参数解析器
        
        :return: 配置好的 ArgumentParser 实例
        """
        ...
    def _register_builtin_commands(self: object) -> ...:
        """
        注册所有内置命令
        """
        ...
    def _load_external_commands(self: object) -> ...:
        """
        加载第三方 CLI 命令
        
        保持与旧版本的兼容性，通过 entry_points 加载第三方命令
        """
        ...
    def _print_version(self: object) -> ...:
        """
        打印版本信息
        """
        ...
    def run(self: object) -> ...:
        """
        运行 CLI
        
        :raises KeyboardInterrupt: 用户中断时抛出
        :raises Exception: 命令执行失败时抛出
        """
        ...
    def _execute_external_command(self: object, args: ...) -> ...:
        """
        执行第三方命令
        
        :param args: 解析后的参数
        """
        ...
