# type: ignore
#
# Auto-generated type stub for registry.py
# DO NOT EDIT MANUALLY - Generated by generate-type-stubs.py
#

"""
CLI 命令注册器

负责命令的注册、查找和管理
"""

from typing import Optional, List, Dict
from .base import Command

class CommandRegistry:
    """
    命令注册器
    
    管理所有已注册的 CLI 命令
    
    {!--< tips >!--}
    1. 使用单例模式确保全局唯一
    2. 支持命令的动态注册和查找
    3. 支持第三方命令的兼容
    {!--< /tips >!--}
    
    :ivar _commands: 已注册的命令字典 {name: Command}
    """
    def __new__(cls: object) -> ...:
        """
        实现单例模式
        """
        ...
    def register(self: object, command: Command) -> ...:
        """
        注册命令
        
        :param command: 要注册的命令实例
        :raises ValueError: 命令名称已存在时抛出
        """
        ...
    def register_external(self: object, name: str, command: Command) -> ...:
        """
        注册第三方命令
        
        :param name: 命令名称
        :param command: 命令实例
        """
        ...
    def get(self: object, name: str) -> Optional[Command]:
        """
        获取命令
        
        :param name: 命令名称
        :return: 命令实例，未找到返回 None
        """
        ...
    def get_all(self: object) -> List[Command]:
        """
        获取所有命令（包括外部命令）
        
        :return: 所有命令列表
        """
        ...
    def list_all(self: object) -> List[str]:
        """
        列出所有命令名称
        
        :return: 命令名称列表
        """
        ...
    def list_builtin(self: object) -> List[str]:
        """
        列出内置命令名称
        
        :return: 内置命令名称列表
        """
        ...
    def list_external(self: object) -> List[str]:
        """
        列出外部命令名称
        
        :return: 外部命令名称列表
        """
        ...
    def exists(self: object, name: str) -> bool:
        """
        检查命令是否存在
        
        :param name: 命令名称
        :return: 命令是否存在
        """
        ...
    def clear_external(self: object) -> ...:
        """
        清空外部命令
        """
        ...
