name: 🎀 Eris PyPI Publish

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Version check
        id: version
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo "Current version: $CURRENT_TAG"

          if [[ $CURRENT_TAG =~ \.dev|\.alpha|\.beta ]]; then
            BASE_VERSION=$(echo $CURRENT_TAG | sed -E 's/([0-9]+)$//')
            PREV_TAG=$(git tag --sort=-v:refname | grep "^$BASE_VERSION" | grep -v "$CURRENT_TAG" | head -n 1)

            if [ -z "$PREV_TAG" ]; then
              echo "Previous version not found"
              exit 1
            fi
            echo "Found previous pre-release version: $PREV_TAG"
            git checkout $PREV_TAG
            echo "use_current=false" >> $GITHUB_OUTPUT
          else
            echo "Stable release"
            echo "use_current=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # - name: Generate type stubs
      #   run: |
      #     python scripts/tools/generate-type-stubs.py --src src --output src --clean --force
      #     echo "Type stubs generation complete"
      # 存根生成器存在一些缺陷，暂时停止使用
      # 详见 CONTRIBUTING.md -> 注解存根生成

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: [release-build]
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/erispulse

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        id: publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true

      - name: Read recipient list
        id: get_emails
        run: |
          emails=$(cat .github/config/notify.json | jq -c '.emails')
          echo "emails=$emails" >> $GITHUB_OUTPUT
